//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry_in_the_work_book
    {
        public int ID { get; set; }
        public Nullable<int> Id_personal_card { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Id_mixing { get; set; }
    
        public virtual Mixing Mixing { get; set; }
        public virtual Personal_card Personal_card { get; set; }
    }
}
