//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_card()
        {
            this.Entry_in_the_work_book = new HashSet<Entry_in_the_work_book>();
            this.Salary = new HashSet<Salary>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Series_and_number { get; set; }
        public string Issued_by_whom { get; set; }
        public Nullable<System.DateTime> Date_of_issue { get; set; }
        public string Registration_address { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> Children { get; set; }
        public Nullable<bool> Military_service { get; set; }
        public byte[] Photo { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_citizenship { get; set; }
        public Nullable<int> Id_post { get; set; }
        public Nullable<int> Id_education { get; set; }
        public string Birthplace { get; set; }
        public string Email { get; set; }
        public string EducationInstitution { get; set; }
    
        public virtual Citizenship Citizenship { get; set; }
        public virtual Education Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry_in_the_work_book> Entry_in_the_work_book { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salary { get; set; }
    }
}
